### ISSUE TITLE
Freshbooster 

### ISSUE THREAD

**Issue by spvrtan** [berbb/PortAIO#272] opened 2016-06-14 04:53 UTC
Q Calc for minion kills is off a lot of the time, it doesnt use Q at all in last hit. Also wastes a lot of Q's on 1 minion rather than being able to get multiple at a time

**Comment by spvrtan** [comment] 2016-06-14 04:54
Q Calc for minion kills is off a lot of the time, it doesnt use Q at all in last hit. Also wastes a lot of Q's on 1 minion rather than being able to get multiple at a time

**Comment by berbb** [comment] 2016-06-14 04:57
Which champion?

**Comment by spvrtan** [comment] 2016-06-14 04:57
Oops sorry buddy, swear i put it in the title.. Freshbooster veigar, my bad

**Comment by berbb** [comment] 2016-06-14 05:51
Pushed updates that improve Q collision so that it makes sure to calculate minions and minion behind it to get maximum stacks as possible. It wasn't using Q in last hit mode because there was no option/code for last hit mode. But with the latest update I added support for last hit. 

Try it out, hopefully it's better.

**Comment by spvrtan** [comment] 2016-06-14 08:06
Q Damage calc is still a little off, leaves them with 5< hp sometimes, it is taking into account the collision now though, working a lot better

**Comment by berbb** [comment] 2016-06-17 04:02
Alright, sorry I taken my attention off of this but I added a slider to reduce the Q damage when clearing so it hits more accurately, similar to the damage reduction slider in Kalista scripts.

The calculations should be perfect according the the damage library but when I compared the Damage Library calculation to the Wiki Veigar page it's the exact same but in game it was off so hopefully this slider helps. I'll be closing this since you confirmed it worked better and since this issue is a bit old.

**Closed by berbb** 2016-06-17 04:02 UTC
