### ISSUE TITLE
Champion Feedback

### ISSUE THREAD

**Issue by Shazelol** [berbb/PortAIO#14] opened 2016-04-28 21:43 UTC
I play with Kalista(KS with E works well, perfect calculations)
Darius(perfect ks R)
Rengar Perfect combo.. issues with E prediction.
Sivir ( W laneclear, jungle clear, harass don't work. E don't work. Q common prediction and OKTW pred works. Ks with Q work.

Excellent work, Berb. (I would have liked to try Ezevade :) )

I will test later.

best regards.

PD: sorry for my bad english, I'm spanish.

**Comment by berbb** [comment] 2016-04-28 23:01
I'll check out Sivir, thanks for the feedback :)

**Comment by Shazelol** [comment] 2016-04-29 02:28
ElVarus don't work in combo, harass anything.
Pls check, good job ;)

**Comment by Xelamats** [comment] 2016-04-29 03:09
I hope I am not intruding by posting here.

@Shazelol 
You can try out the EzEvade port here: https://github.com/MeLoDagG/Elobuddy
Works very well and is kept updated.

**Comment by Shazelol** [comment] 2016-04-29 03:31
Ntp thanks for the link m8.

**Comment by KiriharaSenpai** [comment] 2016-04-29 08:47
lux works well to me try clear appdata and try again and active w in combo settings

**Comment by KiriharaSenpai** [comment] 2016-04-29 09:18
tried khazix and works awesome even if with humanizer

**Comment by berbb** [comment] 2016-04-29 20:34
Jinx doesn't have jungleclear, there's really nothing to really jungle clear with. If it's not an essential feature then I probably won't add it (OKTW Jinx doesn't have it). 

The Lux doesn't really prioritize how many to hit, it prioritize who's the lowest.

I'm testing Varus right now.

**Comment by berbb** [comment] 2016-04-29 20:38
Didn't mean to close it, keep reporting issues!

**Comment by Xelamats** [comment] 2016-04-29 21:27
Kassadin is working amazingly, tested with humanizer. I'm certain without it it is godlike.

**Comment by hardique** [comment] 2016-04-29 21:50
smbdy checked Ezreal?prediction is awesome,but for me no use Q for farm(or lasthit unkillable).

**Comment by berbb** [comment] 2016-04-29 22:08
@hardique Thanks, fixing it right now :)

**Comment by hardique** [comment] 2016-04-29 22:17
@berbb thanks dude.

will test vayne and twitch a little bit later.
btw idk why,but don`t have baseult or lastpredicted pos ult settings in menu.or is it disabled?

**Comment by berbb** [comment] 2016-04-29 22:17
@hardique It's disabled.

**Comment by hardique** [comment] 2016-04-29 22:19
@berbb got it.
tnx for ez fix,will try it right now at high diam :D

**Comment by Muse30** [comment] 2016-04-29 22:27
orianna is godlike 10-0 D2 :smile:

**Comment by hardique** [comment] 2016-04-29 22:29
@Muse30 was waiting for ori script so much.will test in next ranked.

**Comment by Muse30** [comment] 2016-04-29 22:44
not a bug but a suggestion : can you make a keybind toggle to change the combo mode on diana? so I dont have to open the menu everytime to change it xD (Idk if you accept suggestions that are not on the original addon so..)

**Comment by berbb** [comment] 2016-04-29 22:54
@Muse30 Sure, I'll definitely do that :)

**Comment by Xelamats** [comment] 2016-04-30 00:46
Ashe is amazing. No complaints from me. Even got a double kill with auto Ult in FOW lol.

**Comment by hardique** [comment] 2016-04-30 01:03
can confirm,Orianna is godlike.
awesome prediction,smart usage,just wow.

**Comment by hardique** [comment] 2016-04-30 01:12
vayne : just no comments :dancer: 
condemn logic-sorry,but ALL EB ADDONS JUST SUCK.
a lot of different styles for Q and E.
awesome antigapcloser.
just didn`t find out if it uses Q to kill unkillable minions.

**Comment by berbb** [comment] 2016-04-30 01:14
@Muse30 Sorry it took me so long, was completing the to-do list, but it's done, update it and you'll find that 'L' changes the R logic and you'll find this on your screen : http://i.imgur.com/39uKyjB.png

**Comment by hardique** [comment] 2016-04-30 01:23
iKalista Reborn-great.nice dmg calculations,many features(which noone of EB have).
didn`t get to test Balista :(

**Comment by hardique** [comment] 2016-04-30 01:41
kog mao : nice pred,good humanizer ,everything is great ,BUT:

need option to use R in combo mode if target is lower than X % of health (imho,65%-45%-25%)
or smthing like that,but the idea is clear.
if it is possible-would be great.

**Comment by Muse30** [comment] 2016-04-30 01:51
@Berb no problem. thanks

**Comment by GreatWhite181** [comment] 2016-04-30 02:44
Berb, you are a GOD. Thanks for doing so much for all of us, constantly fixing errors let alone porting the best for ALL champs <3

**Comment by Shazelol** [comment] 2016-04-30 04:14
I test Ryze: R combo don't work. Laneclear don't work. W antigapcloser works. Ks i don't test :P 
Keep to perfect pasive(3) works and Stack tear works.

**Comment by berbb** [comment] 2016-04-30 04:25
@Shazelol Made an update to the combo, test it out :)

**Comment by Shazelol** [comment] 2016-04-30 04:51
Wow, Amazing combo, smart use R excellent without humanizer is broken, with humanizer is also too op. Good job, Sir. But ks, laneclear and harass don't work, but is no important. 
Keep it up. Thanks for your hard work in PorAIO(only addon for carry) ;)

**Comment by berbb** [comment] 2016-04-30 05:46
@Shazelol Alright, I fixed laneclear, harass, and killsteal. LaneClear only uses skills when minion is killable (that's how it is in ExorAIO).

**Comment by Shazelol** [comment] 2016-04-30 05:53
I testing Ashe now is really good. All works fine.

**Comment by Shazelol** [comment] 2016-04-30 07:59
I test Cass.. Combo works fine.. really fast E. Amazing R's
Harass works. Laneclear and jungleclear don't work. 
PD: check Ignite and heal %hp.. for me don't work very well.
best regards,.

**Comment by hardique** [comment] 2016-04-30 15:31
@berbb is it possible to add R in combo when lower than 55% for Kog?
or it is only depends from author of original addon?

**Comment by berbb** [comment] 2016-04-30 16:56
@hardique Yeah, it's on my TD list

**Comment by hardique** [comment] 2016-04-30 17:21
@berbb ty dude.
also played ez one more time and noticed no spell usage on jungle clear.

**Comment by dsljkeee** [comment] 2016-04-30 17:30
Jhin ultimate interrupted after two or three shots
and is there any way to make to choose the direction of ultimate
sorry for the English

**Comment by berbb** [comment] 2016-04-30 17:40
@dsljkeee When Jhin's ultimate is active the orbwalker is completely disabled until it's finished or until **you** manually break it, but the KillSteal might have broke the ult so I pushed an update to stop the KS feature when R is active. There is a way to choose the direction of the ult and you have to use semi-manual, you ult yourself in the direction you want and then just press the semi-manual key.

**Comment by harnonsinho** [comment] 2016-04-30 19:16
@berbb Have you ported orbwalk too? if yes its override eb orbwalker?

**Comment by berbb** [comment] 2016-04-30 19:29
@harnonsinho No, I didn't port the orbwalker.

**Comment by hardique** [comment] 2016-04-30 19:31
@berbb r u not planing to port orbw,berbb?

played luc for 3 games,seems a little bit weird for me.I mean script totally,but will try it more.
I saw u r planing to port another luc.

regarding this luc-no jungclear usage spells.

**Comment by berbb** [comment] 2016-04-30 19:34
@hardique No not at all, there's tons of bugs.

-

Last time I checked Lucian jungle was working perfectly in the jungle. I'll test it.

**Comment by hardique** [comment] 2016-04-30 19:35
@berbb played like 10 min ago-no single spell when pressing V.
 
regarding orb : ah,I see.then it has no sense,for sure.

**Comment by berbb** [comment] 2016-04-30 19:47
@hardique Just checked and it's working perfectly fine. Although you might have laneclear/jungle clear on different keys so I pushed a fix for that.

**Comment by harnonsinho** [comment] 2016-04-30 20:17
@berbb  Orianna is waiting too much for cast Q, using Common Prediction, hitchance Medium, can you take a look? :+1:

**Comment by berbb** [comment] 2016-04-30 20:27
@harnonsinho Updated but it still might not be as fast. I recommend using OKTW Prediction for Ori.

**Comment by Shazelol** [comment] 2016-04-30 20:39
@berbb I suggest about pred because sometimes this bad pred or your create own pred ;)
Lulu: I would have liked to lulu out mid / top but the addon is only for supp.

**Comment by harnonsinho** [comment] 2016-04-30 20:40
@Shazelol but he ported LS common pred and LS pred > EB pred

**Comment by Shazelol** [comment] 2016-04-30 20:42
@harnonsinho yep but sometimes LS pred it's not good for many champ... OKTW is better in sine situations :)

**Comment by berbb** [comment] 2016-04-30 20:43
@Shazelol Lulu is already on my to-do list.

**Comment by hardique** [comment] 2016-04-30 21:07
@berbb thx a lot for R for Kog Maw.will check it right now.

**Comment by dsljkeee** [comment] 2016-04-30 22:10
victor don't cast spells for me

**Comment by berbb** [comment] 2016-04-30 22:12
@Shazelol Lulu "re-work" completed, she's now using LuluLicious by Tree's.

**Comment by berbb** [comment] 2016-04-30 22:14
@dsljkeee Just tested, he is casting spells.

**Comment by iiChopper** [comment] 2016-04-30 22:29
Crashes on respawn with blitzcrank some times.

**Comment by berbb** [comment] 2016-04-30 22:34
@iiChopper This was brought up before but I can't reproduce it so I don't know how to fix it.

**Comment by iiChopper** [comment] 2016-04-30 22:35
@berbb Alright, Thanks for the response :)

**Comment by Xelamats** [comment] 2016-04-30 22:35
Yeah, doesn't happen to me either. Tried reproducing it on my end.

**Comment by berbb** [comment] 2016-04-30 22:35
@iiChopper Oh, do you play on fullscreen or borderless?

**Comment by iiChopper** [comment] 2016-04-30 22:38
@berbb I think fullscreen not sure,Going to check it. I'll set it bordeless

**Comment by Xelamats** [comment] 2016-04-30 22:38
I would say to check if you have an updated .Net framework too/MS Build tools.

**Comment by iiChopper** [comment] 2016-04-30 22:39
@Xelamats I have them updated :p

**Comment by Xelamats** [comment] 2016-04-30 22:40
What OS are you on?

**Comment by iiChopper** [comment] 2016-04-30 22:40
Windows 7 ultimate 64bits.

**Comment by Xelamats** [comment] 2016-04-30 22:41
I'm on the same and am facing no problems. Hm.. Try out the Borderless suggestion from Berb.

**Comment by iiChopper** [comment] 2016-04-30 22:42
Sure.

**Comment by Shazelol** [comment] 2016-04-30 23:22
@berbb I tried this new lulu, is best addon for agressive mid top or sup. GJ BERB <3

**Comment by hardique** [comment] 2016-05-01 00:42
@berbb can u check pls vayne jungleclear?
no using Q and E

**Comment by GreatWhite181** [comment] 2016-05-01 00:55
@berbb For me, I fixed my spells not casting, along with any other errors i was getting by deleting my Elobuddy folder in AppData. Maybe add that to comment/Readme

**Comment by DannyTheGod** [comment] 2016-05-01 07:12
Xerath : dont auto cast R and the pridiction is bad, can you check it

**Comment by berbb** [comment] 2016-05-01 07:20
@DannyTheGod I'll check the auto R, but you can mess around with the prediction in the settings.

**Comment by harnonsinho** [comment] 2016-05-01 16:43
@berbb  can you activate SPred in oktw aio menu?

**Comment by berbb** [comment] 2016-05-01 16:46
@harnonsinho It's not good on EB at all, the spells are heavily delayed and it's causing crashes.

**Comment by harnonsinho** [comment] 2016-05-01 16:49
@berbb ok

**Comment by hardique** [comment] 2016-05-01 17:38
@berbb Anivia`s Laneclear is working strange.
R usage almost under champ for 1-2 minions instead of R under 4-5 minions.

**Comment by Shazelol** [comment] 2016-05-01 17:51
@berbb I tried Ashe it's really good OKTW is really monster, but I don't know this option "Auto E" For me don't work.

**Comment by berbb** [comment] 2016-05-01 17:57
@Shazelol Woops, I disabled it on accident. Fixed, update :)

**Comment by rman200** [comment] 2016-05-01 19:54
Sion's Q is only released when its fully charged (plenty of time so enemies walk out of it) 
Would be nice to have it released as enemies are closing to getting out instead(or maybe only use it when theyre on CC)

ps: that may be hard as I've once tried to make a sion assembly but couldnt figure it out
ps2: you can try checking SimpleSion for his logic

**Comment by berbb** [comment] 2016-05-01 19:59
@rman200 Pressing Right Click releases the Q hold.

**Comment by Shazelol** [comment] 2016-05-01 21:10
@berbb I test vayne E condenm don't work(only prada condenm, perfect fast, etc..) But really love with sharpshooter condenm :) I can't test others condenm because I was playing ranked game. :+1:

**Comment by iNubbish** [comment] 2016-05-01 21:19
I personally really like SAC for both options @Shazelol but, to each man their own.

**Comment by hardique** [comment] 2016-05-02 00:45
no using W in Laneclear and harass for Xerath.

**Comment by berbb** [comment] 2016-05-02 00:47
@hardique Checking.

**Comment by berbb** [comment] 2016-05-02 00:53
@hardique It's working, but make sure these are your prediction settings. http://i.imgur.com/fpsax5M.png - or try medium. OKTW is bad with Xerath,

**Comment by hardique** [comment] 2016-05-02 01:32
@berbb thanks,seems like now working.
as I understood,for orianna it is also better to use common pred?

**Comment by berbb** [comment] 2016-05-02 02:02
@hardique For some reason every champion in OKTW has different experiences with prediction. For Ori I like to use OKTW.

**Comment by hardique** [comment] 2016-05-02 08:20
@berbb didn`t notice about Xerath R,is it using it auto ,when smbdy is killable?

**Comment by berbb** [comment] 2016-05-02 11:42
@hardique Completely forgot about that, I'll check it out.

**Comment by hardique** [comment] 2016-05-02 15:23
@berbb common pred is now that good,tbh,for Xerath.
idk what to do.

**Comment by berbb** [comment] 2016-05-02 20:51
@hardique I've enabled SPrediction, try it out it may be better. Also, Auto R is working, I've tested it in game and it's working well.

**Comment by hardique** [comment] 2016-05-02 20:54
@berbb thx,will try it out right now.cuz Hellsing`s Xerath doesn`t use W for LaneClear and it makes me crazy :(
will give a feedback about SPred.should I change something for SPred to be enabled?

**Comment by berbb** [comment] 2016-05-02 20:55
@hardique Yes, you enable it by going to OKTW Menu and slide it to 2, play around with it in a custom to see what you like.

**Comment by hardique** [comment] 2016-05-02 20:57
@berbb got it,thx.

**Comment by Muse30** [comment] 2016-05-02 21:19
@berbb  oh nice I will test spred too

**Comment by hardique** [comment] 2016-05-02 22:09
@berbb not casting Q and other spells on Xerath with SPred.

**Comment by berbb** [comment] 2016-05-02 22:31
@hardique Working fine. http://i.imgur.com/xhig7W9.gif

**Comment by kchamp64** [comment] 2016-05-02 23:30
Played the new ProjectFiora pretty much everything was flawless except that for the W non-skillshot menus there's no option to turn it off, it's only for evade skillshots. I think you should either unify turning on all W evading under that one key or add extra keys under the other menus for all non-skillshot W evading.

**Comment by hardique** [comment] 2016-05-02 23:49
@berbb i don`t have spred submenu(

**Comment by Xelamats** [comment] 2016-05-02 23:51
Try deleting your Elobuddy folder in Appdata.

**Comment by kchamp64** [comment] 2016-05-02 23:52
Is SPred supposed to show up under every champ? Or just certain ones.

**Comment by hardique** [comment] 2016-05-02 23:53
@Xelamats nvm,i am an idiot.forgot to f5

**Comment by berbb** [comment] 2016-05-02 23:54
@kchamp64 Only OKTW supported champs.

**Comment by berbb** [comment] 2016-05-03 00:17
@Xelamats Added your awesome logo! Tell me it's displaying oddly on the screen (x & y-wise).

**Comment by hardique** [comment] 2016-05-03 00:47
anivia with oktw pred on med-high is better than spred,imo.

**Comment by Xelamats** [comment] 2016-05-03 00:54
@berbb 

Doing a quick modification right now so it stands out more. Currently, it looks odd in my opinion. Will only take one second. Will create a preview screen of it as well. :)

**Comment by Shazelol** [comment] 2016-05-03 04:04
@berbb I play with garen and my addon is active but.. He is spam Q E :/ and I don't pressing key.

**Comment by dsljkeee** [comment] 2016-05-03 19:03
Kayle don't use r

**Comment by rpgfreak128** [comment] 2016-05-05 00:42
@berbb not sure if this has been reported already but fiddlesticks cancels W maybe i need change some settings? and it does not use E on champion

**Comment by hardique** [comment] 2016-05-05 04:44
when using semi-manual cast R on lucian-something cancels ult early.
pls,take a look at it,berbb.

**Comment by Luc4z** [comment] 2016-05-05 11:00
@berbb God Jungle Tracker is updated in official site for info .

**Comment by berbb** [comment] 2016-05-06 02:50
@Luc4z Packet Events aren't working on EB at all so it can't capture it anyway.

**Comment by lushisop** [comment] 2016-05-10 02:00
game crashing when changing from Valvare Yasuo to YasuoPro

**Comment by rpgfreak128** [comment] 2016-05-14 03:15
@berbb two issues. natutalis Q not working in combo killsteal works, and when we report an issue about a champ how do we nkow it got fixed?

**Comment by berbb** [comment] 2016-05-14 03:34
@rpgfreak128 I reply or look at the commits.

**Closed** 2016-05-16 04:43 UTC
