### ISSUE TITLE
Champions: Brand and Varus

### ISSUE THREAD

**Issue by TheRealZeagan** [berbb/PortAIO#25] opened 2016-05-20 14:27 UTC
Brand:
Brand is not using e in laneclear.
Holding V. It uses W and Q's not no e's. It is enabled in settings.

Varus:
Varus not orbwalking while using Q.
Varus q is sometimes really off. even if I change the prediction hitbox thing. (Varus shooting q asap without hitting anything.

**Comment by nothology** [comment] 2016-05-20 16:04
When I played both like 1 hr ago, they worked just fine..and Varus q was amazingly accurate.

**Comment by PortAIOMuse** [comment] 2016-05-20 16:15
fixed the not orwalking while Q but the couldnt reproduce the prediction error

**Comment by TheRealZeagan** [comment] 2016-05-20 16:20
Uhm. Its like I hold Spacebar down, and it shoots 1 good and then when the CD is ready again it fails all the rest. I have to Spacebar, then stop then Spacebar. Like I have to spam spacebar.

Also its OKTV Brand that does not use e. I used TheBrand and its working really good.

**Comment by nothology** [comment] 2016-05-20 16:21
Yes I tried the Brand too. But it is weird when I played Varus, all worked as it should.

**Comment by PortAIOMuse** [comment] 2016-05-20 16:57
E in laneclear should be fixed

**Closed** 2016-05-20 17:15 UTC
