### ISSUE TITLE
Game crashing from time to time - SDKPredictioner problem?

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#343] opened 2016-06-19 15:02 UTC
Everytime I play with it I sometimes encounter crash. There is nothing in console. Like 5 mins ago I was playing Valvrave Lee with EzEvade, ElUtilSuite and SDKPred enabled. When I pressed the Combo key, game freezed & crashed

**Comment by inphratiic** [comment] 2016-06-19 15:40
that is probably a crash caused by valvrave lee , it's a known issue for a while and they are still working on a fix

**Comment by DjVrip** [comment] 2016-06-19 22:54
Same for me, This is the first time it did this to me

**Comment by DjVrip** [comment] 2016-06-19 22:55
I playing Irelia just have ElUtil & SDK and at the time of spawn (after launching) LoL crash

**Comment by berbb** [comment] 2016-06-20 12:55
Alright, I just pushed some changes to Berb.Common and PortAIO. Hopefully they fix the issues.

**Comment by lgndz** [comment] 2016-06-22 09:28
Just leavign feedback -

Still going unresponsive at load in of game. Happens with any champ

**Comment by berbb** [comment] 2016-06-22 11:50
@lgndz Then its a utility, list your utilities.

**Comment by lgndz** [comment] 2016-06-22 21:29
Ive been messaging you on Discord but the utilities are as such (from memory since Ihave not been able to load in);

Activator - NABB
Tracker - NABB
SDKPredictioner
EBPredictioner
ezEvade (all advanced options on, FASTEST) (FOW, Dodge only dangerous)
SkinChanger (was activated, didnt use)
UniversalGankAlerter
AutoLevel (god blesS)

**Comment by lgndz** [comment] 2016-06-22 21:39
Newest test.

Deleted EVERYTHING EB releated and all pre reqs
Reinstalled
Repaired LoL

Loaded DEFAULT PortAIO 
Akali hero

XQX Akali
All default Utilites
Loaded 100%

Modified utils to
ElUtility Suite
NabbTracker
EBPred
ezEvade
UniGank Alerter
UniRecall Tracker

reloaded 100%.


Dont know what this means, but Akali seems to work fine

**Comment by berbb** [comment] 2016-06-24 18:23
Should be fixed with previous updates.

**Closed by berbb** 2016-06-24 18:23 UTC
